"""initial

Revision ID: 90f5610bf67d
Revises: 0b9faabc3524
Create Date: 2025-03-10 12:38:49.735377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f5610bf67d'
down_revision: Union[str, None] = '0b9faabc3524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_project', sa.Column('project_role', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_project', 'project_role')
    # ### end Alembic commands ###
